package com.erickuha.iching.oracle

enum class Hexagram (val hexagramNumber: Int, val textName: String){
    FORCE(1, "force"),
    FIELD(2, "field"),
    SPROUTING(3, "sprouting"),
    ENVELOPING(4, "enveloping"),
    ATTENDING(5, "attending"),
    CONFLICT(6, "conflict"),
    LEADING(7, "leading"),
    GROUPING(8, "grouping"),
    LITTLE_ACCUMULATION(9, "little_accumulation"),
    TREADING(10, "treading"),
    PEACE(11, "peace"),
    STANDSTILL(12, "standstill"),
    FELLOWSHIP(13, "fellowship"),
    GREAT_POSSESSION(14, "great_possession"),
    MODESTY(15, "modesty"),
    ENTHUSIASM(16, "enthusiasm"),
    FOLLOWING(17, "following"),
    CORRECTING(18, "correcting"),
    NEARING(19, "nearing"),
    CONTEMPLATION(20, "contemplation"),
    BITING_THROUGH(21, "biting_through"),
    GRACE(22, "grace"),
    SPLITTING_APART(23, "splitting_apart"),
    RETURN(24, "return"),
    INNOCENCE(25, "innocence"),
    GREAT_ACCUMULATION(26, "great_accumulation"),
    NOURISHING(27, "nourishing"),
    GREAT_EXCEEDING(28, "great_exceeding"),
    GORGE(29, "gorge"),
    RADIANCE(30, "radiance"),
    INFLUENCE(31, "influence"),
    PERSEVERING(32, "persevering"),
    RETREAT(33, "retreat"),
    GREAT_STRENGTH(34, "great_strength"),
    PROGRESS(35, "progress"),
    BRILLIANCE_INJURED(36, "brilliance_injured"),
    FAMILY(37, "family"),
    OPPOSITION(38, "opposition"),
    OBSTRUCTION(39, "obstruction"),
    DELIVERANCE(40, "deliverance"),
    DECREASING(41, "decreasing"),
    INCREASING(42, "increasing"),
    BREAKTHROUGH(43, "breakthrough"),
    COMING_TO_MEET(44, "coming_to_meet"),
    GATHERING_TOGETHER(45, "gathering_together"),
    GROWING_UPWARD(46, "growing_upward"),
    OPPRESSION(47, "oppression"),
    THE_WELL(48, "the_well"),
    REVOLUTION(49, "revolution"),
    THE_CAULDRON(50, "the_cauldron"),
    AROUSING_THUNDER(51, "arousing_thunder"),
    KEEPING_STILL(52, "keeping_still"),
    DEVELOPMENT(53, "development"),
    MARRYING_MAIDEN(54, "marrying_maiden"),
    ABUNDANCE(55, "abundance"),
    WANDERER(56, "wanderer"),
    GENTLE_WIND(57, "gentle_wind"),
    JOYOUS_LAKE(58, "joyous_lake"),
    DISPERSING(59, "dispersing"),
    LIMITATION(60, "limitation"),
    INNER_TRUTH(61, "inner_truth"),
    LITTLE_EXCEEDING(62, "little_exceeding"),
    AFTER_COMPLETION(63, "after_completion"),
    BEFORE_COMPLETION(64, "before_completion");

    companion object {
        private val map = Hexagram.values().associateBy { it.hexagramNumber}
        operator fun get(value: Int) = map[value]
    }
}