package com.erickuha.iching.oracle

import com.erickuha.iching.R

enum class Hexagram (val hexagramNumber: Int, resId: Int) {//val textName: String){
    FORCE(1, R.array.force),
    FIELD(2, R.array.field),
    SPROUTING(3, R.array.sprouting),
    ENVELOPING(4, R.array.enveloping),
    ATTENDING(5, R.array.attending),
    CONFLICT(6, R.array.conflict),
    LEADING(7, R.array.leading),
    GROUPING(8, R.array.grouping),
    LITTLE_ACCUMULATION(9, R.array.little_accumulation),
    TREADING(10, R.array.treading),
    PEACE(11, R.array.peace),
    STANDSTILL(12, R.array.standstill),
    FELLOWSHIP(13, R.array.fellowship),
    GREAT_POSSESSION(14, R.array.great_possession),
    MODESTY(15, R.array.modesty),
    ENTHUSIASM(16, R.array.enthusiasm),
    FOLLOWING(17, R.array.following),
    CORRECTING(18, R.array.correcting),
    NEARING(19, R.array.nearing),
    CONTEMPLATION(20, R.array.contemplation),
    BITING_THROUGH(21, R.array.biting_through),
    GRACE(22, R.array.grace),
    SPLITTING_APART(23, R.array.splitting_apart),
    RETURNING(24, R.array.returning),
    INNOCENCE(25, R.array.innocence),
    GREAT_ACCUMULATION(26, R.array.great_accumulation),
    NOURISHING(27, R.array.nourishing),
    GREAT_EXCEEDING(28, R.array.great_exceeding),
    GORGE(29, R.array.gorge),
    RADIANCE(30, R.array.radiance),
    INFLUENCE(31, R.array.influence),
    PERSEVERING(32, R.array.persevering),
    RETREAT(33, R.array.retreat),
    GREAT_STRENGTH(34, R.array.great_strength),
    PROGRESS(35, R.array.progress),
    BRILLIANCE_INJURED(36, R.array.brilliance_injured),
    FAMILY(37, R.array.family),
    OPPOSITION(38, R.array.opposition),
    OBSTRUCTION(39, R.array.obstruction),
    DELIVERANCE(40, R.array.deliverance),
    DECREASING(41, R.array.decreasing),
    INCREASING(42, R.array.increasing),
    BREAKTHROUGH(43, R.array.breakthrough),
    COMING_TO_MEET(44, R.array.coming_to_meet),
    GATHERING_TOGETHER(45, R.array.gathering_together),
    GROWING_UPWARD(46, R.array.growing_upward),
    OPPRESSION(47, R.array.oppression),
    THE_WELL(48, R.array.the_well),
    REVOLUTION(49, R.array.revolution),
    THE_CAULDRON(50, R.array.the_cauldron),
    AROUSING_THUNDER(51, R.array.arousing_thunder),
    KEEPING_STILL(52, R.array.keeping_still),
    DEVELOPMENT(53, R.array.development),
    MARRYING_MAIDEN(54, R.array.marrying_maiden),
    ABUNDANCE(55, R.array.abundance),
    WANDERER(56, R.array.wanderer),
    GENTLE_WIND(57, R.array.gentle_wind),
    JOYOUS_LAKE(58, R.array.joyous_lake),
    DISPERSING(59, R.array.dispersing),
    LIMITATION(60, R.array.limitation),
    INNER_TRUTH(61, R.array.inner_truth),
    LITTLE_EXCEEDING(62, R.array.little_exceeding),
    AFTER_COMPLETION(63, R.array.after_completion),
    BEFORE_COMPLETION(64, R.array.before_completion);

    companion object {
        private val map = Hexagram.values().associateBy { it.hexagramNumber}
        operator fun get(value: Int) = map[value]
    }
}